// reference for store fields and actions to preserve my sanity
const GET_COMMENT_CHAIN = 'GET_COMMENT_CHAIN';
const CHANGE_REPLY_VISIBILITY = 'CHANGE_REPLY_VISIBILITY'
const SUBMIT_COMMENT = 'SUBMIT_COMMENT';

export {
  GET_COMMENT_CHAIN,
  CHANGE_REPLY_VISIBILITY,
  SUBMIT_COMMENT
}